name: download_data
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - requests=2.31.0
  - pip=23.2.1
  - mlflow=2.7.1
  - hydra-core=1.3.2
  - pip:
      - wandb==0.15.11
      - hydra-joblib-launcher==1.2.0