name: download_data
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pandas=2.0.3
  - pip=23.2.1
  - scikit-learn=1.1.2
  - matplotlib=3.7.3
  - plotly=5.17.0
  - pillow=10.0.1
  - mlflow=2.7.1
  - pip:
      - wandb==0.15.11
